using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using ThreadSafetClassAnalyser.Model;

namespace ThreadSafetClassAnalyser.Utils
{
    public static class AnalyzerUtils
    {
        /// <summary>
        /// Searches the class lock associations to find which lock objects (targets) 
        /// are being used inside a specific member (method, lambda, etc.).
        /// </summary>
        /// <param name="lockMap">The map generated by GetClassLockAssociationDict.</param>
        /// <param name="memberSymbol">The symbol of the method or lambda to check.</param>
        /// <returns>A list of symbols representing the objects being locked.</returns>
        public static IEnumerable<ISymbol> GetLockObjectsUsedInMember(
            ClassLocks lockMap, 
            ISymbol memberSymbol)
        {
            if (memberSymbol == null) yield break;

            foreach (var entry in lockMap)
            {
                var lockObject = entry.Key;
                var associations = entry.Value;

                // Check if any association in this lock group belongs to our target member
                if (associations.Any(a => SymbolEqualityComparer.Default.Equals(a.MemberContainingLock, memberSymbol)))
                {
                    yield return lockObject;
                }
            }
        }
        
        private const int MaxAnalysisDepth = 10;

        public static bool IsInternallySynchronized(
            IMethodSymbol methodSymbol, 
            SemanticModel semanticModel, 
            int currentDepth = 0, 
            HashSet<IMethodSymbol> visited = null)
        {
            // 1. Terminal cases & Performance Guards
            if (methodSymbol == null || currentDepth > MaxAnalysisDepth) return false;
            
            if (visited == null)
            {
                visited = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
            }

            if (!visited.Add(methodSymbol)) return false;

            // 2. Metadata Check: Include SemaphoreSlim as an inherently safe system primitive
            var typeName = methodSymbol.ContainingType?.ToDisplayString();
            if (typeName == KnownTypes.FullInterlockedName || 
                typeName == KnownTypes.FullVolatileName || 
                typeName == KnownTypes.FullMonitorName ||
                typeName == KnownTypes.FullSemaphoreSlimName)
            {
                return true;
            }

            var syntaxRef = methodSymbol.DeclaringSyntaxReferences.FirstOrDefault();
            if (syntaxRef == null) return false;

            var syntax = syntaxRef.GetSyntax();

            // 4. Intra-procedural Check
            if (syntax.DescendantNodes().OfType<LockStatementSyntax>().Any())
                return true;

            // 5. Inter-procedural Check
            var invocations = syntax.DescendantNodes().OfType<InvocationExpressionSyntax>();
            foreach (var invocation in invocations)
            {
                var invokedSymbol = semanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
                if (invokedSymbol == null) 
                    continue;

                // Optimization: Only step into calls within the same class boundary
                if (!SymbolEqualityComparer.Default.Equals(invokedSymbol.ContainingType, methodSymbol.ContainingType))
                {
                    var extTypeName = invokedSymbol.ContainingType?.ToDisplayString();
                    // Match external calls against the expanded primitive list
                    if (extTypeName == KnownTypes.FullInterlockedName || 
                        extTypeName == KnownTypes.FullVolatileName || 
                        extTypeName == KnownTypes.FullMonitorName ||
                        extTypeName == KnownTypes.FullSemaphoreSlimName)
                    {
                        return true;
                    }
                    continue; 
                }

                // RECURSION
                if (IsInternallySynchronized(invokedSymbol, semanticModel, currentDepth + 1, visited))
                {
                    return true;
                }
            }

            return false;
        }
        
        public static bool IsInsideThreadSafePrimitive(SyntaxNode node, SemanticModel semanticModel)
        {
            // Walk up the tree to see if this identifier is an argument in a method call
            var invocation = node.Ancestors().OfType<InvocationExpressionSyntax>().FirstOrDefault();
            if (invocation == null) return false;

            var symbol = semanticModel.GetSymbolInfo(invocation).Symbol;
            if (symbol == null) return false;

            var containingTypeName = symbol.ContainingType?.ToDisplayString();

            return containingTypeName == KnownTypes.FullInterlockedName || 
                   containingTypeName == KnownTypes.FullVolatileName;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="threadCreation"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        public static Dictionary<ISymbol, AccessInfo> GetAccessedFieldsFromExpression(ObjectCreationExpressionSyntax threadCreation, SemanticModel model)
        {
            // Change instantiation to AccessInfo
            var accessed = new Dictionary<ISymbol, AccessInfo>(SymbolEqualityComparer.Default);
    
            var lambda = threadCreation.ArgumentList?.Arguments.FirstOrDefault()?.Expression;

            if (lambda == null) return accessed;

            // Now the types match for this call
            PopulateAccessesRecursive(
                lambda, 
                model,
                accessed, 
                new HashSet<ISymbol>(SymbolEqualityComparer.Default),
                null);

            return accessed;
        }
        
        public static Dictionary<ISymbol, AccessInfo> GetAccessedFieldsFromMethod(MethodDeclarationSyntax methodDecl, SemanticModel model)
        {
            var accessed = new Dictionary<ISymbol, AccessInfo>(SymbolEqualityComparer.Default);

            if (methodDecl == null) return accessed;

            // Pass the entire method body right into your recursive scanner
            PopulateAccessesRecursive(
                methodDecl,
                model,
                accessed,
                new HashSet<ISymbol>(SymbolEqualityComparer.Default),
                null);

            return accessed;
        }

        /// <summary>
        /// Recursively analyzes a syntax node to discover all field and property accesses, 
        /// stepping into invoked local methods while tracking the active locking context.
        /// </summary>
        /// <param name="node">The root syntax node to start scanning from (e.g., a method body).</param>
        /// <param name="model">The semantic model used to resolve symbols and identifiers.</param>
        /// <param name="accessed">A dictionary mapping discovered member symbols to their aggregated access information.</param>
        /// <param name="visitedMethods">A set tracking already analyzed method symbols to prevent infinite loops from recursion or cycles.</param>
        /// <param name="currentLockSymbol">The symbol of the lock currently held in the execution path, or <see langword="null"/> if no lock is explicitly inherited.</param>
        /// <remarks>
        /// This method performs static analysis across two main phases:
        /// <list type="number">
        /// <item>
        /// <description><b>Data Access Tracking:</b> Scans for identifiers representing fields or properties, determines if they are reads or writes via <see cref="IsWriteAccess(IdentifierNameSyntax)"/>, and maps them to the nearest surrounding lock.</description>
        /// </item>
        /// <item>
        /// <description><b>Interprocedural Analysis:</b> Identifies method invocations, propagates the current lock context to the call site, and recursively scans the declaring syntax of the target method.</description>
        /// </item>
        /// </list>
        /// </remarks>
        private static void PopulateAccessesRecursive(
            SyntaxNode node,
            SemanticModel model,
            IDictionary<ISymbol, AccessInfo> accessed,
            HashSet<ISymbol> visitedMethods,
            ISymbol currentLockSymbol)
        {
            // Capture manual lock contexts dynamically when entering a method or accessor root
            var activeLock = currentLockSymbol;
            if (node is MethodDeclarationSyntax || node is AccessorDeclarationSyntax)
            {
                // Call your helper to check if this method sets up a manual try-finally lock
                var manualLock = GetManualLockSymbolIfAny(node, model);
                if (manualLock != null)
                {
                    activeLock = manualLock;
                }
            }

            // 1. Manual Scan for Fields/Properties
            var identifiers = node.DescendantNodes().OfType<IdentifierNameSyntax>();
            foreach (var id in identifiers)
            {
                if (id.Ancestors().OfType<AttributeSyntax>().Any()) 
                    continue;
                
                var info = model.GetSymbolInfo(id);
                var sym = info.Symbol ?? info.CandidateSymbols.FirstOrDefault();
                

                if (sym == null ||
                    (sym.Kind != SymbolKind.Field && sym.Kind != SymbolKind.Property)) continue;
                
                var isWrite = IsWriteAccess(id);
                
                // Use the dynamically discovered manual lock if a syntactic ancestor lock is missing
                var effectiveLock = activeLock ?? LockAssociationUtils.GetFirstAncestorLockFromSymbol(id, model);
                    
                var isVolatile = (sym is IFieldSymbol field && field.IsVolatile);
                var isAtomicCall = IsInsideThreadSafePrimitive(id, model);
                
                UpdateAccessMap(accessed, sym, isWrite ? AccessType.Write : AccessType.Read, effectiveLock, isVolatile, isAtomicCall);
            }

            // 2. Process Invocations (Stepping into methods)
            var invocations = node.DescendantNodes().OfType<InvocationExpressionSyntax>();
            foreach (var invocation in invocations)
            {
                if (!(model.GetSymbolInfo(invocation).Symbol is IMethodSymbol methodSymbol)) continue;
                if (!visitedMethods.Add(methodSymbol)) continue;

                // Cascade the active lock symbol context down to callee methods during the jump
                var lockAtCallSite = activeLock ?? LockAssociationUtils.GetFirstAncestorLockFromSymbol(invocation, model);
                foreach (var reference in methodSymbol.DeclaringSyntaxReferences)
                {
                    var methodSyntax = reference.GetSyntax();
                    PopulateAccessesRecursive(methodSyntax, model, accessed, visitedMethods, lockAtCallSite);
                }
            }
        }

        /// <summary>
        /// Determines whether a given <see cref="IdentifierNameSyntax"/> represents a write operation (mutation) to a variable.
        /// </summary>
        /// <param name="identifier">The identifier token to evaluate.</param>
        /// <returns>
        /// <see langword="true"/> if the identifier is the target of an assignment expression or part of a unary 
        /// increment/decrement operation; otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// This method walks up the syntax tree to resolve complex member or element accesses 
        /// (e.g., tracing <c>obj.NestedProperty.Field</c> up to its assignment context) before 
        /// checking for mutating expressions like <c>=</c>, <c>+=</c>, <c>++</c>, or <c>--</c>.
        /// Note: if the identifier resolves to an element access (e.g. <c>arr[i] = val</c>) or a
        /// parenthesized expression on the left-hand side, it is treated as a read � only the element
        /// is written, not the field itself.
        /// </remarks>
        public static bool IsWriteAccess(IdentifierNameSyntax identifier)
        {
            SyntaxNode current = identifier;

            // Walk up through member accesses (obj.Field) to find the full expression being assigned to.
            while (current.Parent is MemberAccessExpressionSyntax || current.Parent is ElementAccessExpressionSyntax)
            {
                // If the identifier is inside bracket arguments (e.g. arr[field]) or a parenthesized
                // expression, the field is only being read � not written.
                if (current.Parent is ElementAccessExpressionSyntax elementAccess && elementAccess.Expression != current)
                    return false;

                if (current.Parent is ParenthesizedExpressionSyntax)
                    return false;

                current = current.Parent;
            }

            // If the walked-up expression is itself an element access (e.g. _array[i] = val),
            // the field is only read to obtain the collection reference � not written.
            if (current is ElementAccessExpressionSyntax)
                return false;

            var parent = current.Parent;

            // 1. Check for assignment: current = value;
            if (parent is AssignmentExpressionSyntax assignment && assignment.Left == current)
            {
                return true;
            }

            // 2. Check for increment/decrement: current++;
            return parent is PostfixUnaryExpressionSyntax || parent is PrefixUnaryExpressionSyntax;
        }

        /// <summary>
        /// Updates or initializes the access tracking record for a specific shared symbol and its locking strategy.
        /// </summary>
        /// <param name="map">The state map correlating symbols with their aggregated <see cref="AccessInfo"/>.</param>
        /// <param name="symbol">The field or property symbol being accessed.</param>
        /// <param name="type">The type of access detected (<see cref="AccessType.Read"/> or <see cref="AccessType.Write"/>).</param>
        /// <param name="currentLock">The symbol representing the lock object protecting this specific access, or <see langword="null"/>.</param>
        /// <param name="isVolatile">The symbol is a volatile type</param>
        /// <param name="isAtomicCall">Uses Interlocked to call</param>
        /// <remarks>
        /// <b>Lock Poisoning Logic:</b> If a symbol is accessed multiple times across different code paths, 
        /// its attributes are aggregated. A <see cref="AccessType.Write"/> will permanently overwrite a <see cref="AccessType.Read"/>. 
        /// Crucially, if the symbol is accessed under two <i>different</i> locks (or locked in one place but unlocked in another), 
        /// the <see cref="AccessInfo.LockObject"/> is permanently set to <see langword="null"/>, indicating inconsistent synchronization.
        /// </remarks>
        private static void UpdateAccessMap(
            IDictionary<ISymbol, AccessInfo> map, 
            ISymbol symbol, 
            AccessType type, 
            ISymbol currentLock,
            bool isVolatile,
            bool isAtomicCall)
        {
            if (map.TryGetValue(symbol, out var existing))
            {
                if (type == AccessType.Write) existing.AccessType = AccessType.Write;
        
                // If one access is locked and another isn't, LockObject becomes null (inconsistent)
                if (!SymbolEqualityComparer.Default.Equals(existing.LockObject, currentLock))
                {
                    existing.LockObject = null; 
                }
        
                // Accumulate atomic properties
                existing.IsVolatile |= isVolatile;
                existing.IsAtomicCall |= isAtomicCall;
            }
            else
            {
                map[symbol] = new AccessInfo 
                { 
                    AccessType = type, 
                    LockObject = currentLock,
                    IsVolatile = isVolatile,
                    IsAtomicCall = isAtomicCall
                };
            }
        }

        /// <summary>
        /// This method finds conflicting accesses between two Symbols and their field & property accesses.
        /// </summary>
        /// <param name="method1AccessMap">A Dict associating Symbols with <see cref="AccessInfo"/> access entries from the method</param>
        /// <param name="method2AccessMap">A Dict associating Symbols with <see cref="AccessInfo"/> access entries from the method</param>
        /// <returns>A list of symbols that have conflicting accesses where at least one is a write operation</returns>
        public static IEnumerable<ISymbol> FindConflicts(
            Dictionary<ISymbol, AccessInfo> method1AccessMap, 
            Dictionary<ISymbol, AccessInfo> method2AccessMap)
        {
            foreach (var field in method1AccessMap.Keys)
            {
                if (!method2AccessMap.TryGetValue(field, out var info2)) continue;
                var info1 = method1AccessMap[field];
                
                
                // 1. Basic conflict check (at least one write)
                if (info1.AccessType == AccessType.Write || info2.AccessType == AccessType.Write)
                {
                    yield return field;
                }
            }
        }
        
        /// <summary>
        /// Find all ObjectCreationsExpressions from the <see cref="context"/> nodes Descendant nodes.
        /// </summary>
        /// <param name="context">The current SyntaxNodeAnalysisContext.</param>
        /// <param name="semanticModel">The current nodes Semantic model.</param>
        /// <param name="typeSymbol"> A typePrefix from the <see cref="KnownTypes"/> file (e.g. Thread or Task).</param>
        /// <returns>A list of all ObjectCreationExpressionSyntax of type <see cref="KnownTypes"/> in the class.</returns>
        public static List<ObjectCreationExpressionSyntax> GetObjectCreationsInClass(SyntaxNodeAnalysisContext context, SemanticModel semanticModel, string typeSymbol)
        {
            if (!(context.Node is ClassDeclarationSyntax classDecl)) return null;
            
            return classDecl.DescendantNodes()
                .OfType<ObjectCreationExpressionSyntax>()
                .Where(oc => {
                    var type = semanticModel.GetTypeInfo(oc).Type;
                    return type?.Name.Contains(typeSymbol) == true;
                })
                .ToList();
        }
        
        /// <summary>
        /// Determines whether a full memory fence (barrier) exists between two syntax nodes in program order.
        /// </summary>
        /// <param name="root">The root node of the syntax tree to search within.</param>
        /// <param name="start">The starting syntax node (typically a write operation).</param>
        /// <param name="end">The ending syntax node (typically a read operation).</param>
        /// <param name="model">The semantic model used to resolve symbols for method invocations.</param>
        /// <returns>
        /// True if a full memory fence is detected between <paramref name="start"/> 
        /// and <paramref name="end"/>; otherwise false.
        /// </returns>
        public static bool HasFullFenceBetween(SyntaxNode root, SyntaxNode start, SyntaxNode end, SemanticModel model)
        {
            var startPos = start.SpanStart;
            var endPos = end.SpanStart;

            // Identify all nodes between the Write and Read in Program Order
            var nodesInBetween = root.DescendantNodes()
                .Where(n => n.SpanStart > startPos && n.SpanStart < endPos);

            foreach (var node in nodesInBetween)
            {
                // Check for Thread.MemoryBarrier()
                if (node is InvocationExpressionSyntax invocation)
                {
                    var symbol = model.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
                    if (symbol != null)
                    {
                        var containingType = symbol.ContainingType.ToDisplayString();
                        var methodName = symbol.Name;

                        // Thread.MemoryBarrier() � explicit full fence
                        if (containingType == KnownTypes.FullThreadName && methodName == KnownTypes.MemoryBarrier)
                            return true;

                        // Interlocked.* � no read or write can move past an interlocked operation in either direction
                        // Covers: Exchange, CompareExchange, Add, Increment, Decrement, Read, Or, And
                        // https://learn.microsoft.com/en-us/archive/msdn-magazine/2005/october/understanding-low-lock-techniques-in-multithreaded-apps
                        if (containingType == KnownTypes.FullInterlockedName)
                            return true;

                        // Monitor.Enter / Monitor.TryEnter � acquire fence
                        // Monitor.Exit � release fence
                        // Together (or individually between a write and read) they act as a full fence
                        if (containingType == KnownTypes.FullMonitorName &&
                            (methodName == "Enter" || methodName == "Exit" || methodName == "TryEnter"))
                            return true;
                    }
                }

                // lock statement � full fence on both entry (acquire) and exit (release)
                // Syntactic sugar over Monitor.Enter / Monitor.Exit
                if (node is LockStatementSyntax)
                    return true;
            }

            return false;
        }
        
        /// <summary>
        /// Compares the locking mechanisms of two <see cref="AccessInfo"/> objects to determine if they sync on the same object.
        /// </summary>
        /// /// <remarks>
        /// The <see cref="AccessInfo"/> instances can be retrieved using <see cref="GetAccessedFieldsFromExpression"/>.
        /// </remarks>
        /// <param name="info1">The first <see cref="AccessInfo"/></param>
        /// <param name="info2">The second <see cref="AccessInfo"/></param>
        /// <returns>
        /// <see langword="true"/> if both objects are explicitly locked using the exact same symbol; 
        /// otherwise, <see langword="false"/>. Returns <see langword="false"/> if either lock object is <see langword="null"/>.
        /// </returns>
        public static bool IsUsingSameLockObject(AccessInfo info1, AccessInfo info2)
        {
            return info1.LockObject != null && 
                   info2.LockObject != null && 
                   SymbolEqualityComparer.Default.Equals(info1.LockObject, info2.LockObject);
        }
        
        /// <summary>
        /// Returns <see langword="true"/> if <paramref name="node"/> is protected by the
        /// <c>Monitor.Enter</c> / <c>Monitor.Exit</c> manual-lock pattern � i.e. a
        /// <c>Monitor.Enter</c> call precedes it in the method body, and it is enclosed
        /// in a try/finally whose finally block calls <c>Monitor.Exit</c>.
        /// </summary>
        public static bool IsInsideMonitorEnterRegion(SyntaxNode node, SemanticModel model)
        {
            var nodePos = node.SpanStart;

            // 1. The node must be enclosed in a try/finally where the finally releases the lock
            var coveringTry = node.Ancestors()
                .OfType<TryStatementSyntax>()
                .FirstOrDefault(t => t.Finally != null && HasMonitorExitInFinally(t.Finally, model));

            if (coveringTry == null) return false;

            // 2. A Monitor.Enter/TryEnter call must appear before this node in the method body
            var methodBody = node.Ancestors()
                .Select(a =>
                {
                    if (a is MethodDeclarationSyntax m)
                        return m.Body as SyntaxNode;
                    if (a is AnonymousFunctionExpressionSyntax f)
                        return f.Body;
                    return null;
                })
                .FirstOrDefault(b => b != null);

            if (methodBody == null) return false;

            return methodBody.DescendantNodes()
                .OfType<InvocationExpressionSyntax>()
                .Any(inv =>
                {
                    if (inv.SpanStart >= nodePos) return false;
                    var symbol = model.GetSymbolInfo(inv).Symbol as IMethodSymbol;
                    return symbol?.ContainingType.ToDisplayString() == KnownTypes.FullMonitorName &&
                           (symbol.Name == "Enter" || symbol.Name == "TryEnter");
                });
        }

        /// <summary>
        /// Returns <see langword="true"/> if the given finally clause contains a
        /// <c>Monitor.Exit</c> call � indicating a manually managed lock release.
        /// </summary>
        private static bool HasMonitorExitInFinally(FinallyClauseSyntax finallyClause, SemanticModel model)
        {
            return finallyClause.DescendantNodes()
                .OfType<InvocationExpressionSyntax>()
                .Any(inv =>
                {
                    var symbol = model.GetSymbolInfo(inv).Symbol as IMethodSymbol;
                    return symbol?.ContainingType.ToDisplayString() == KnownTypes.FullMonitorName &&
                           symbol.Name == "Exit";
                });
        }
        
        private static IFieldSymbol FindLocksFieldSymbol(INamedTypeSymbol typeSymbol)
        {
            // 1. Search current class level fields for the '_locks' identifier
            var field = typeSymbol.GetMembers().OfType<IFieldSymbol>().FirstOrDefault(f => f.Name == "_locks");
            if (field != null) return field;

            // 2. Recurse into nested classes (like the Tables block) using a separate variable
            foreach (var nestedType in typeSymbol.GetTypeMembers())
            {
                var nestedField = FindLocksFieldSymbol(nestedType);
                if (nestedField != null) return nestedField;
            }
            return null;
        }

        public static ISymbol GetManualLockSymbolIfAny(SyntaxNode methodSyntax, SemanticModel semanticModel)
        {
            var tryStmts = methodSyntax.DescendantNodes().OfType<TryStatementSyntax>();
            foreach (var tryStmt in tryStmts)
            {
                if (tryStmt.Finally == null) continue;

                // 1. Inspect the finally block for explicit lock releases
                var finallyInvocations = tryStmt.Finally.DescendantNodes().OfType<InvocationExpressionSyntax>();
                bool releasesLock = false;
                foreach (var inv in finallyInvocations)
                {
                    if (semanticModel.GetSymbolInfo(inv).Symbol is IMethodSymbol methodSymbol)
                    {
                        if (methodSymbol.Name == "Exit" || methodSymbol.Name.Contains("ReleaseLocks"))
                        {
                            releasesLock = true;
                            break;
                        }
                    }
                }

                if (!releasesLock) continue;

                // 2. Inspect the overarching scope or try block for companion acquisitions
                var tryAndBodyInvocations = methodSyntax.DescendantNodes().OfType<InvocationExpressionSyntax>();
                bool acquiresLock = false;
                foreach (var inv in tryAndBodyInvocations)
                {
                    if (semanticModel.GetSymbolInfo(inv).Symbol is IMethodSymbol methodSymbol)
                    {
                        if (methodSymbol.Name == "Enter" || methodSymbol.Name.Contains("Acquire"))
                        {
                            acquiresLock = true;
                            break;
                        }
                    }
                }

                // 3. Unify the operations under the shared striped lock reference boundary
                if (acquiresLock)
                {
                    var containingClass = methodSyntax.Ancestors().OfType<ClassDeclarationSyntax>().FirstOrDefault();
                    if (containingClass != null)
                    {
                        if (semanticModel.GetDeclaredSymbol(containingClass) is INamedTypeSymbol classSymbol)
                        {
                            var locksField = FindLocksFieldSymbol(classSymbol);
                            if (locksField != null) return locksField;
                        }
                    }
                }
            }
            return null;
        }
    }
}