//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadSafetClassAnalyser {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThreadSafetClassAnalyser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string FieldUsedTitle {
            get {
                return ResourceManager.GetString("FieldUsedTitle", resourceCulture);
            }
        }
        
        internal static string FieldUsedMessageFormat {
            get {
                return ResourceManager.GetString("FieldUsedMessageFormat", resourceCulture);
            }
        }
        
        internal static string FieldUsedDescription {
            get {
                return ResourceManager.GetString("FieldUsedDescription", resourceCulture);
            }
        }
        
        internal static string FieldAccessedExternallyTitle {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyTitle", resourceCulture);
            }
        }
        
        internal static string FieldAccessedExternallyMessageFormat {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyMessageFormat", resourceCulture);
            }
        }
        
        internal static string FieldAccessedExternallyDescription {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyDescription", resourceCulture);
            }
        }
        
        internal static string FieldDoesNotUseLockDescription {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockDescription", resourceCulture);
            }
        }
        
        internal static string FieldDoesNotUseLockTitle {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockTitle", resourceCulture);
            }
        }
        
        internal static string FieldDoesNotUseLockMessageFormat {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockMessageFormat", resourceCulture);
            }
        }
        
        internal static string TestRuleTitle {
            get {
                return ResourceManager.GetString("TestRuleTitle", resourceCulture);
            }
        }
        
        internal static string TestRuleDescription {
            get {
                return ResourceManager.GetString("TestRuleDescription", resourceCulture);
            }
        }
        
        internal static string TestRuleMessageFormat {
            get {
                return ResourceManager.GetString("TestRuleMessageFormat", resourceCulture);
            }
        }
        
        internal static string InternalFieldNoLockTitle {
            get {
                return ResourceManager.GetString("InternalFieldNoLockTitle", resourceCulture);
            }
        }
        
        internal static string InternalFieldNoLockDescription {
            get {
                return ResourceManager.GetString("InternalFieldNoLockDescription", resourceCulture);
            }
        }
        
        internal static string InternalFieldNoLockMessageFormat {
            get {
                return ResourceManager.GetString("InternalFieldNoLockMessageFormat", resourceCulture);
            }
        }
        
        internal static string LockObjectExposedTitle {
            get {
                return ResourceManager.GetString("LockObjectExposedTitle", resourceCulture);
            }
        }
        
        internal static string LockObjectExposedDescription {
            get {
                return ResourceManager.GetString("LockObjectExposedDescription", resourceCulture);
            }
        }
        
        internal static string LockObjectExposedMessageFormat {
            get {
                return ResourceManager.GetString("LockObjectExposedMessageFormat", resourceCulture);
            }
        }
        
        internal static string PublicFieldExposedTitle {
            get {
                return ResourceManager.GetString("PublicFieldExposedTitle", resourceCulture);
            }
        }
        
        internal static string PublicFieldExposedDescription {
            get {
                return ResourceManager.GetString("PublicFieldExposedDescription", resourceCulture);
            }
        }
        
        internal static string PublicFieldExposedMessageFormat {
            get {
                return ResourceManager.GetString("PublicFieldExposedMessageFormat", resourceCulture);
            }
        }
        
        internal static string ConflictingAccessThreadTitle {
            get {
                return ResourceManager.GetString("ConflictingAccessThreadTitle", resourceCulture);
            }
        }
        
        internal static string ConflictingAccessThreadMessageFormat {
            get {
                return ResourceManager.GetString("ConflictingAccessThreadMessageFormat", resourceCulture);
            }
        }
        
        internal static string ConflictingAccessThreadDescription {
            get {
                return ResourceManager.GetString("ConflictingAccessThreadDescription", resourceCulture);
            }
        }
        
        internal static string SP001Title {
            get {
                return ResourceManager.GetString("SP001Title", resourceCulture);
            }
        }
        
        internal static string SP001MessageFormat {
            get {
                return ResourceManager.GetString("SP001MessageFormat", resourceCulture);
            }
        }
        
        internal static string SP001Description {
            get {
                return ResourceManager.GetString("SP001Description", resourceCulture);
            }
        }
        
        internal static string SP003Title {
            get {
                return ResourceManager.GetString("SP003Title", resourceCulture);
            }
        }
        
        internal static string SP003MessageFormat {
            get {
                return ResourceManager.GetString("SP003MessageFormat", resourceCulture);
            }
        }
        
        internal static string SP003Description {
            get {
                return ResourceManager.GetString("SP003Description", resourceCulture);
            }
        }
        
        internal static string VolatileReorderingTitle {
            get {
                return ResourceManager.GetString("VolatileReorderingTitle", resourceCulture);
            }
        }
        
        internal static string VolatileReorderingMessageFormat {
            get {
                return ResourceManager.GetString("VolatileReorderingMessageFormat", resourceCulture);
            }
        }
        
        internal static string VolatileReorderingDescription {
            get {
                return ResourceManager.GetString("VolatileReorderingDescription", resourceCulture);
            }
        }
        
        internal static string InconsistentLockUseTitle {
            get {
                return ResourceManager.GetString("InconsistentLockUseTitle", resourceCulture);
            }
        }
        
        internal static string InconsistentLockUseDescription {
            get {
                return ResourceManager.GetString("InconsistentLockUseDescription", resourceCulture);
            }
        }
        
        internal static string InconsistentLockUseMessageFormat {
            get {
                return ResourceManager.GetString("InconsistentLockUseMessageFormat", resourceCulture);
            }
        }
        
        internal static string LockOnClassInstanceTitle {
            get {
                return ResourceManager.GetString("LockOnClassInstanceTitle", resourceCulture);
            }
        }
        
        internal static string LockOnClassInstanceDescription {
            get {
                return ResourceManager.GetString("LockOnClassInstanceDescription", resourceCulture);
            }
        }
        
        internal static string LockOnClassInstanceMessageFormat {
            get {
                return ResourceManager.GetString("LockOnClassInstanceMessageFormat", resourceCulture);
            }
        }
        
        internal static string ConflictingAccessRuleTitle {
            get {
                return ResourceManager.GetString("ConflictingAccessRuleTitle", resourceCulture);
            }
        }
        
        internal static string ConflictingAccessRuleDescription {
            get {
                return ResourceManager.GetString("ConflictingAccessRuleDescription", resourceCulture);
            }
        }
        
        internal static string ConflictingAccessRuleMessageFormat {
            get {
                return ResourceManager.GetString("ConflictingAccessRuleMessageFormat", resourceCulture);
            }
        }
        
        internal static string MonitorNotPairedTitle {
            get {
                return ResourceManager.GetString("MonitorNotPairedTitle", resourceCulture);
            }
        }
        
        internal static string MonitorNotPairedMessageFormat {
            get {
                return ResourceManager.GetString("MonitorNotPairedMessageFormat", resourceCulture);
            }
        }
        
        internal static string MonitorNotPairedDescription {
            get {
                return ResourceManager.GetString("MonitorNotPairedDescription", resourceCulture);
            }
        }
        
        internal static string MonitorNotInFinallyTitle {
            get {
                return ResourceManager.GetString("MonitorNotInFinallyTitle", resourceCulture);
            }
        }
        
        internal static string MonitorNotInFinallyMessageFormat {
            get {
                return ResourceManager.GetString("MonitorNotInFinallyMessageFormat", resourceCulture);
            }
        }
        
        internal static string MonitorNotInFinallyDescription {
            get {
                return ResourceManager.GetString("MonitorNotInFinallyDescription", resourceCulture);
            }
        }
        
        internal static string MonitorConflictingAccessTitle {
            get {
                return ResourceManager.GetString("MonitorConflictingAccessTitle", resourceCulture);
            }
        }
        
        internal static string MonitorConflictingAccessMessageFormat {
            get {
                return ResourceManager.GetString("MonitorConflictingAccessMessageFormat", resourceCulture);
            }
        }
        
        internal static string MonitorConflictingAccessDescription {
            get {
                return ResourceManager.GetString("MonitorConflictingAccessDescription", resourceCulture);
            }
        }
        
        internal static string SP002Title {
            get {
                return ResourceManager.GetString("SP002Title", resourceCulture);
            }
        }
        
        internal static string SP002Description {
            get {
                return ResourceManager.GetString("SP002Description", resourceCulture);
            }
        }
        
        internal static string SP002MessageFormat {
            get {
                return ResourceManager.GetString("SP002MessageFormat", resourceCulture);
            }
        }
    }
}
