//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadSafetClassAnalyser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreadSafetClassAnalyser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase.
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters. .
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple class members access the same mutable field concurrently without a shared lock, where at least one operation is a write. This can introduce data races and memory reordering bugs.
        /// </summary>
        internal static string ConflictingAccessRuleDescription {
            get {
                return ResourceManager.GetString("ConflictingAccessRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{1}()&apos; can conflict with method &apos;{2}()&apos; on the shared state &apos;{0}&apos; because they lack proper synchronization and at least one method is a write operation..
        /// </summary>
        internal static string ConflictingAccessRuleMessageFormat {
            get {
                return ResourceManager.GetString("ConflictingAccessRuleMessageFormat", resourceCulture);
            }
        }
        
<<<<<<< HEAD
        /// <summary>
        ///   Looks up a localized string similar to Conflicting access to shared mutable state across members.
        /// </summary>
        internal static string ConflictingAccessRuleTitle {
            get {
                return ResourceManager.GetString("ConflictingAccessRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting accesses in threads where atleast one access is a write.
        /// </summary>
        internal static string ConflictingAccessThreadDescription {
            get {
                return ResourceManager.GetString("ConflictingAccessThreadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a conflicting access on field &apos;{0}&apos; between Thread &apos;{1}&apos; and Thread &apos;{2}&apos;.
        /// </summary>
        internal static string ConflictingAccessThreadMessageFormat {
            get {
                return ResourceManager.GetString("ConflictingAccessThreadMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting access between threads.
        /// </summary>
        internal static string ConflictingAccessThreadTitle {
            get {
                return ResourceManager.GetString("ConflictingAccessThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warns when a field or property is accessed from outside its declaring class, which may indicate state escape or a violation of encapsulation.
        /// </summary>
        internal static string FieldAccessedExternallyDescription {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property &apos;{0}&apos; is accessed from outside its declaring class &apos;{1}&apos;.
        /// </summary>
        internal static string FieldAccessedExternallyMessageFormat {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field or property accessed outside declaring class.
        /// </summary>
        internal static string FieldAccessedExternallyTitle {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn when a field or property accessor is publicly visible and doesn&apos;t use a lock.
        /// </summary>
        internal static string FieldDoesNotUseLockDescription {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accessor &apos;{0}&apos; in &apos;{1}&apos; can be called from outside its declaring class and doesn&apos;t use a lock.
        /// </summary>
        internal static string FieldDoesNotUseLockMessageFormat {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessor is publicly available but doesn&apos;t use a lock.
        /// </summary>
        internal static string FieldDoesNotUseLockTitle {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warns when a field is used in any method.
        /// </summary>
        internal static string FieldUsedDescription {
            get {
                return ResourceManager.GetString("FieldUsedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is used in method &apos;{1}&apos;.
        /// </summary>
        internal static string FieldUsedMessageFormat {
            get {
                return ResourceManager.GetString("FieldUsedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field used in method.
        /// </summary>
        internal static string FieldUsedTitle {
            get {
                return ResourceManager.GetString("FieldUsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this field or property is not always synchronized by the same lock.
        /// </summary>
        internal static string InconsistentLockUseDescription {
            get {
                return ResourceManager.GetString("InconsistentLockUseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; uses lock &apos;{1}&apos; but other places it uses lock &apos;{2}&apos;.
        /// </summary>
        internal static string InconsistentLockUseMessageFormat {
            get {
                return ResourceManager.GetString("InconsistentLockUseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent Lock usage on field or property.
        /// </summary>
        internal static string InconsistentLockUseTitle {
            get {
                return ResourceManager.GetString("InconsistentLockUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal field or property not properly synchronized.
        /// </summary>
        internal static string InternalFieldNoLockDescription {
            get {
                return ResourceManager.GetString("InternalFieldNoLockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; in &apos;{1}&apos; is exposed through method &apos;{2}&apos; without a lock.
        /// </summary>
        internal static string InternalFieldNoLockMessageFormat {
            get {
                return ResourceManager.GetString("InternalFieldNoLockMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field or property not properly synchronized.
        /// </summary>
        internal static string InternalFieldNoLockTitle {
            get {
                return ResourceManager.GetString("InternalFieldNoLockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lock object is being exposed via a public accessor.
        /// </summary>
        internal static string LockObjectExposedDescription {
            get {
                return ResourceManager.GetString("LockObjectExposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lock &apos;{0}&apos; in class &apos;{1}&apos; is publicly exposed via accessor &apos;{2}&apos;.
        /// </summary>
        internal static string LockObjectExposedMessageFormat {
            get {
                return ResourceManager.GetString("LockObjectExposedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock object publicly exposed.
        /// </summary>
        internal static string LockObjectExposedTitle {
            get {
                return ResourceManager.GetString("LockObjectExposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking on &apos;this&apos; exposes the sync object to external callers, which can lead to deadlocks.
        /// </summary>
        internal static string LockOnClassInstanceDescription {
            get {
                return ResourceManager.GetString("LockOnClassInstanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &apos;{0}&apos; uses &apos;lock (this)&apos; in method &apos;{1}&apos;. This can cause deadlocks if external code also locks on the instance. Use a private lock object instead.
        /// </summary>
        internal static string LockOnClassInstanceMessageFormat {
            get {
                return ResourceManager.GetString("LockOnClassInstanceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use &apos;lock (this)&apos;.
        /// </summary>
        internal static string LockOnClassInstanceTitle {
            get {
                return ResourceManager.GetString("LockOnClassInstanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field accessed inside a &apos;Monitor.Enter&apos;/&apos;Monitor.Exit&apos; critical section is also accessed in another method without equivalent synchronization. This can introduce data races.
        /// </summary>
        internal static string MonitorConflictingAccessDescription {
            get {
                return ResourceManager.GetString("MonitorConflictingAccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{1}()&apos; accesses shared field &apos;{0}&apos; inside a &apos;Monitor&apos; critical section, but method &apos;{2}()&apos; accesses the same field without equivalent synchronization.
        /// </summary>
        internal static string MonitorConflictingAccessMessageFormat {
            get {
                return ResourceManager.GetString("MonitorConflictingAccessMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting access to shared state inside Monitor-guarded region.
        /// </summary>
        internal static string MonitorConflictingAccessTitle {
            get {
                return ResourceManager.GetString("MonitorConflictingAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Monitor.Enter&apos; must be followed immediately by a try block with &apos;Monitor.Exit&apos; in the finally clause. Without this pattern, any exception thrown inside the critical section will permanently hold the lock.
        /// </summary>
        internal static string MonitorNotInFinallyDescription {
            get {
                return ResourceManager.GetString("MonitorNotInFinallyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; calls &apos;Monitor.Enter&apos; on &apos;{1}&apos; without a try/finally block. An exception will prevent &apos;Monitor.Exit&apos; from running and leave the lock permanently acquired.
        /// </summary>
        internal static string MonitorNotInFinallyMessageFormat {
            get {
                return ResourceManager.GetString("MonitorNotInFinallyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.Enter not protected by try/finally.
        /// </summary>
        internal static string MonitorNotInFinallyTitle {
            get {
                return ResourceManager.GetString("MonitorNotInFinallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every &apos;Monitor.Enter&apos; call must be matched by a &apos;Monitor.Exit&apos; call. An unpaired enter will permanently hold the lock, causing deadlocks for all other threads trying to acquire it.
        /// </summary>
        internal static string MonitorNotPairedDescription {
            get {
                return ResourceManager.GetString("MonitorNotPairedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; calls &apos;Monitor.Enter&apos; on &apos;{1}&apos; but has no matching &apos;Monitor.Exit&apos; call. This will cause the lock to never be released.
        /// </summary>
        internal static string MonitorNotPairedMessageFormat {
            get {
                return ResourceManager.GetString("MonitorNotPairedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaired Monitor.Enter call.
        /// </summary>
        internal static string MonitorNotPairedTitle {
            get {
                return ResourceManager.GetString("MonitorNotPairedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public fields break encapsulation. Use properties with appropriate accessor modifiers instead.
        /// </summary>
        internal static string PublicFieldExposedDescription {
            get {
                return ResourceManager.GetString("PublicFieldExposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is public. {1}.
        /// </summary>
        internal static string PublicFieldExposedMessageFormat {
            get {
                return ResourceManager.GetString("PublicFieldExposedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public field exposes internal state.
        /// </summary>
        internal static string PublicFieldExposedTitle {
            get {
                return ResourceManager.GetString("PublicFieldExposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields should be safely published by being readonly, volatile, or initialized to a default value without relying on constructor logic.
        /// </summary>
        internal static string SP001Description {
            get {
                return ResourceManager.GetString("SP001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not safely published. Declare it as &apos;readonly&apos; or &apos;volatile&apos; to ensure safe publication.
        /// </summary>
        internal static string SP001MessageFormat {
            get {
                return ResourceManager.GetString("SP001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not safely published.
        /// </summary>
        internal static string SP001Title {
            get {
                return ResourceManager.GetString("SP001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling a virtual method in a constructor is unsafe when a derived class overrides it and reads fields that are set in the derived constructor body, not in initializers.
        /// </summary>
        internal static string SP003Description {
            get {
                return ResourceManager.GetString("SP003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor of &apos;{0}&apos; calls virtual method &apos;{1}&apos;. A derived class override may run before the derived constructor body, observing uninitialized fields.
        /// </summary>
        internal static string SP003MessageFormat {
            get {
                return ResourceManager.GetString("SP003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual method called in constructor.
        /// </summary>
        internal static string SP003Title {
            get {
                return ResourceManager.GetString("SP003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An anonymous test rule.
        /// </summary>
        internal static string TestRuleDescription {
            get {
                return ResourceManager.GetString("TestRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test rule: &apos;{0}&apos; and &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        internal static string TestRuleMessageFormat {
            get {
                return ResourceManager.GetString("TestRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Rule.
        /// </summary>
        internal static string TestRuleTitle {
            get {
                return ResourceManager.GetString("TestRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In C# a volatile write followed by a volatile read may be reordered without a full-fence memory barrier.
        /// </summary>
        internal static string VolatileReorderingDescription {
            get {
                return ResourceManager.GetString("VolatileReorderingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volatile read &apos;{0}&apos; in method &apos;{1}&apos; is at risk of being reordered to happen before the volatile write &apos;{2}&apos; in the same method.
        /// </summary>
        internal static string VolatileReorderingMessageFormat {
            get {
                return ResourceManager.GetString("VolatileReorderingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible volatile store/load reordering.
        /// </summary>
        internal static string VolatileReorderingTitle {
            get {
                return ResourceManager.GetString("VolatileReorderingTitle", resourceCulture);
=======
        internal static string SP002Title {
            get {
                return ResourceManager.GetString("SP002Title", resourceCulture);
            }
        }
        
        internal static string SP002Description {
            get {
                return ResourceManager.GetString("SP002Description", resourceCulture);
            }
        }
        
        internal static string SP002MessageFormat {
            get {
                return ResourceManager.GetString("SP002MessageFormat", resourceCulture);
>>>>>>> RoslynImplementation
            }
        }
    }
}
