//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadSafetClassAnalyser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreadSafetClassAnalyser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters. .
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warns when a field or property is accessed from outside its declaring class, which may indicate state escape or a violation of encapsulation..
        /// </summary>
        internal static string FieldAccessedExternallyDescription {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property &apos;{0}&apos; is accessed from outside its declaring class &apos;{1}&apos;..
        /// </summary>
        internal static string FieldAccessedExternallyMessageFormat {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field or property accessed outside declaring class.
        /// </summary>
        internal static string FieldAccessedExternallyTitle {
            get {
                return ResourceManager.GetString("FieldAccessedExternallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn when a field or property accessor is publicly visible and doesn&apos;t use a lock..
        /// </summary>
        internal static string FieldDoesNotUseLockDescription {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accessor &apos;{0}&apos; in &apos;{1}&apos; can be called from outside its declaring class and doesn&apos;t use a lock. .
        /// </summary>
        internal static string FieldDoesNotUseLockMessageFormat {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessor is publicly available but doesn&apos;t use a lock..
        /// </summary>
        internal static string FieldDoesNotUseLockTitle {
            get {
                return ResourceManager.GetString("FieldDoesNotUseLockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warns when a field is used in any method..
        /// </summary>
        internal static string FieldUsedDescription {
            get {
                return ResourceManager.GetString("FieldUsedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is used in method &apos;{1}&apos;.
        /// </summary>
        internal static string FieldUsedMessageFormat {
            get {
                return ResourceManager.GetString("FieldUsedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field used in method.
        /// </summary>
        internal static string FieldUsedTitle {
            get {
                return ResourceManager.GetString("FieldUsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields should be safely published by being readonly, volatile, or initialized to a default value without relying on constructor logic..
        /// </summary>
        internal static string SP001Description {
            get {
                return ResourceManager.GetString("SP001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not safely published. Declare it as &apos;readonly&apos; or &apos;volatile&apos; to ensure safe publication..
        /// </summary>
        internal static string SP001MessageFormat {
            get {
                return ResourceManager.GetString("SP001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not safely published.
        /// </summary>
        internal static string SP001Title {
            get {
                return ResourceManager.GetString("SP001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling a virtual method in a constructor is unsafe when a derived class overrides it and reads fields that are set in the derived constructor body, not in initializers..
        /// </summary>
        internal static string SP003Description {
            get {
                return ResourceManager.GetString("SP003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor of &apos;{0}&apos; calls virtual method &apos;{1}&apos;. A derived class override may run before the derived constructor body, observing uninitialized fields..
        /// </summary>
        internal static string SP003MessageFormat {
            get {
                return ResourceManager.GetString("SP003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual method called in constructor.
        /// </summary>
        internal static string SP003Title {
            get {
                return ResourceManager.GetString("SP003Title", resourceCulture);
            }
        }
        
        internal static string TestRuleTitle {
            get {
                return ResourceManager.GetString("TestRuleTitle", resourceCulture);
            }
        }
        
        internal static string TestRuleDescription {
            get {
                return ResourceManager.GetString("TestRuleDescription", resourceCulture);
            }
        }
        
        internal static string TestRuleMessageFormat {
            get {
                return ResourceManager.GetString("TestRuleMessageFormat", resourceCulture);
            }
        }
        
        internal static string InternalFieldNoLockTitle {
            get {
                return ResourceManager.GetString("InternalFieldNoLockTitle", resourceCulture);
            }
        }
        
        internal static string InternalFieldNoLockDescription {
            get {
                return ResourceManager.GetString("InternalFieldNoLockDescription", resourceCulture);
            }
        }
        
        internal static string InternalFieldNoLockMessageFormat {
            get {
                return ResourceManager.GetString("InternalFieldNoLockMessageFormat", resourceCulture);
            }
        }
        
        internal static string LockObjectExposedTitle {
            get {
                return ResourceManager.GetString("LockObjectExposedTitle", resourceCulture);
            }
        }
        
        internal static string LockObjectExposedDescription {
            get {
                return ResourceManager.GetString("LockObjectExposedDescription", resourceCulture);
            }
        }
        
        internal static string LockObjectExposedMessageFormat {
            get {
                return ResourceManager.GetString("LockObjectExposedMessageFormat", resourceCulture);
            }
        }
        
        internal static string PublicFieldExposedTitle {
            get {
                return ResourceManager.GetString("PublicFieldExposedTitle", resourceCulture);
            }
        }
        
        internal static string PublicFieldExposedDescription {
            get {
                return ResourceManager.GetString("PublicFieldExposedDescription", resourceCulture);
            }
        }
        
        internal static string PublicFieldExposedMessageFormat {
            get {
                return ResourceManager.GetString("PublicFieldExposedMessageFormat", resourceCulture);
            }
        }
    }
}
